version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        name: elasticsearch
    steps:
      - checkout
      - restore_cache:
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
