version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        name: elasticsearch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - run: rm -fr .m2 && cp -p -R ~/.m2 .
      - run: docker build -t jena-elasticsearch -f .circleci/Dockerfile .
      - run: docker run jena-elasticsearch bash -c "cd project && mvn test"
      - store_test_results:
          path: target/surefire-reports
