version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        name: elasticsearch
        environment:
          - cluster.name: elasticsearch
          - xpack.security.enabled: false
#          - transport.host: localhost
#          - network.host: 127.0.0.1
#          - http.port: 9200
          - discovery.type: single-node
    steps:
      # Wait for ElasticSearch to come up
      - run: sleep 15
      - checkout
#      - setup_remote_docker
      - restore_cache:
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - run: mvn package
#      - run: rm -fr .m2 && cp -p -R ~/.m2 . && find .m2 | wc
#      - run: docker build -t jena-elasticsearch -f .circleci/Dockerfile .
#      - run: docker run --name jena-elasticsearch jena-elasticsearch bash -c "mvn package test && tail /dev/null"
#      - run: mkdir target && docker cp jena-elasticsearch:target/surefire-reports target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: jena-elasticsearch-m2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
